apiVersion: v1
kind: Pod
metadata:
  name: nlp-lab-match-dont-close-gpu2 #change name
spec:
  restartPolicy: OnFailure

  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
       claimName: id202188507-pvc  #use your id+student ID

  containers:
  - name: nlp-lab-match-dont-close-gpu2 #change name
    image: pusan.local:5000/tf1.15.4-cuda11.1-py3:2021-02-24
    volumeMounts:
    - mountPath: /dev/shm #use your id+student ID
      name: pvc-volume
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "while true; do sleep 30; done;"
    securityContext:
      allowPrivilegeEscalation: false

    resources:
      requests:
        nvidia.com/gpu: 2 #gpu 
      limits:
        nvidia.com/gpu: 2 #gpu 